apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ckbb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ckbb
    app.kubernetes.io/part-of: ci1t-43256-0072-app
  name: devfile-sample-ckbb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ckbb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ckbb
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0072-tenant/ci1t-43256-0072-app/devfile-sample-ckbb@sha256:7b706b12fe0a6c05fb0993d74244a910f6ac12fdbe82ff606f6f9f5ff010f868
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
